version: '2'
services:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8333:80
    environment:
      - PMA_HOST=mysql1
      - PMA_USER=root
      - PMA_PASSWORD=password
      # - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=500M
  
  mysql1:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=k1
      - MYSQL_USER=root1
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./datadir:/var/lib/mysql